name: Lint
on:
    pull_request:
      types:
        - opened
      branches:
        - main
      paths-ignore:
        - '.github/workflows/**'
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Lint
        run: |
          npm ci
          npm run lint