name: SSH command

on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths-ignore:
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    env:
      name: ghcr.io/yevhennsorganization/pizza-backend
      key: "ssh_key"
      stamp: ${GITHUB_SHA}
      host: ${{ secrets.ORACLE_USER }}"@"${{ secrets.ORACLE_IP }}
      ghcr_user: $(echo ${{ github.repository_owner }} | tr '[A-Z]' '[a-z]')

    steps: 
      - name: Delete old images
        uses: snok/container-retention-policy@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          account-type: org
          org-name: yevhennsorganization
          cut-off: 1 min ago UTC
          skip-tags: latest
          image-names: pizza-backend
          dry-run: true