name: SSH command

on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths-ignore:
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    env:
      name: ghcr.io/yevhennsorganization/pizza-backend
      key: "ssh_key"
      stamp: ${GITHUB_SHA}
      host: ${{ secrets.ORACLE_USER }}"@"${{ secrets.ORACLE_IP }}
      ghcr_user: $(echo ${{ github.repository_owner }} | tr '[A-Z]' '[a-z]')
    steps:
    - uses: actions/delete-package-versions@v4
      with: 
        package-name: '${GITHUB_REPOSITORY#*/}'
        package-type: 'container'
        min-versions-to-keep: 1
        ignore-versions: 'latest'